### ISSUE TITLE
Example of client

### ISSUE THREAD

**Issue by raphaelauv** [terrycain/sanic-openid-provider#3]
Hello thank you for your work, but i don't know how to use your little lib.

Could you write a full example with a sanic app and a provider like okta 

Thank you !!

**Comment by raphaelauv** [comment]
`# imports for both Flask and Okta connection

# orginal TUTO https://www.fullstackpython.com/blog/add-user-authentication-flask-apps-okta.html

from flask import Flask, Response, redirect, url_for ,g
from flask_oidc import OpenIDConnect
from okta import UsersClient

app = Flask(__name__)

# secret credentials for Okta connection
conf_file_okta_app = "./Test/openidconnect_secret.json"

app.config["OIDC_CLIENT_SECRETS"] = conf_file_okta_app
app.config["OIDC_COOKIE_SECURE"] = False
app.config["OIDC_CALLBACK_ROUTE"] = "/oidc/callback"
app.config["OIDC_SCOPES"] = ["openid", "email", "profile"]
app.config["SECRET_KEY"] = "clefpriverandompourFLask"
app.config["OIDC_ID_TOKEN_COOKIE_NAME"] = "oidc_token"

oidc = OpenIDConnect(app)

# token = "00BF4F6kondwLHGgk4VZNtp9rVFPHI-s3jPlqvsnNg"
#
# okta_url = "https://dev-499792.oktapreview.com"
# okta_client = UsersClient(okta_url, token)
#
#
# @app.before_request
# def before_request():
#     if oidc.user_loggedin:
#         g.user = okta_client.get_user(oidc.user_getfield("sub"))
#     else:
#         g.user = None


@app.route("/")
@oidc.require_login
def landing_page():
    if oidc.user_loggedin:
        return Response(
            'Hello ' + str(oidc.user_getfield('email')) + '<br /><a href="/logout">Log out</a>')
    else:
        # logically it's impossible
        return Response('Welcome anonymous, <a href="/private">Log in</a>')


@app.route("/login")
@oidc.require_login
def login():
    """Force user to login and then redirect them
    """
    return redirect(url_for(".landing_page"))


@app.route("/logout")
def logout():
    oidc.logout()
    return redirect(url_for(".landing_page"))


if __name__ == '__main__':
    app.run(host="localhost", port=5000, debug=True)
`

**Comment by terricain** [comment]
I'll see if i can whip something together over the weekend.

**Comment by raphaelauv** [comment]
This is a working example with flask , i would like to do the same but with sanic

openidconnect_secret.json ->
```
{
  "web": {
    "client_id": "tttttttttt",
    "client_secret": "tttttttttttttttttttttt",
    "auth_uri": "https://dev-tttttttt.oktapreview.com/oauth2/default/v1/authorize",
    "token_uri": "https://dev-ttttttttttttt.oktapreview.com/oauth2/default/v1/token",
    "issuer": "https://dev-tttttttt.oktapreview.com/oauth2/default",
    "token_introspection_uri": "https://dev-tttttttttt.oktapreview.com/oauth2/default/v1/introspect",
    "userinfo_uri": "https://dev-tttttttttt.oktapreview.com/oauth2/default/userinfo",
    "redirect_uris": [
      "http://localhost:5000/oidc/callback"
    ]
  }
}

```



```python
from flask import Flask, Response, redirect, url_for
from flask_oidc import OpenIDConnect

app = Flask(__name__)

# secret credentials for Okta connection
conf_file_okta_app = "./Test/openidconnect_secret.json"

app.config["OIDC_CLIENT_SECRETS"] = conf_file_okta_app
app.config["OIDC_COOKIE_SECURE"] = False
app.config["OIDC_CALLBACK_ROUTE"] = "/oidc/callback"
app.config["OIDC_SCOPES"] = ["openid", "email", "profile"]
app.config["SECRET_KEY"] = "ttttttttttttttt"
app.config["OIDC_ID_TOKEN_COOKIE_NAME"] = "oidc_token"

oidc = OpenIDConnect(app)


@app.route("/")
@oidc.require_login
def landing_page():
    return Response('OKAY')


@app.route("/login")
@oidc.require_login
def login():
    return redirect(url_for(".landing_page"))


@app.route("/logout")
def logout():
    oidc.logout()
    return redirect(url_for(".landing_page"))


if __name__ == '__main__':
    app.run(host="localhost", port=5000, debug=True)

```

**Comment by terricain** [comment]
Yeah it can be done. The library is mostly to be an oidc provider, on the receiving end of your flask app but out of convenience i made a client library too :smile:.

**Comment by terricain** [comment]
https://github.com/terrycain/sanic-openid-provider/tree/master/examples/okta_openid - this help?

The client library has only been used by me so there are most likely bugs so if you find anything just raise an issue.

**Comment by raphaelauv** [comment]
Thank you very much !! this is well working !

**Comment by terricain** [comment]
Glad to here it, any issues let me know.
