### ISSUE TITLE
requirements version

### ISSUE THREAD

**Issue by raphaelauv** [terrycain/sanic-openid-provider#4]
Hello ! 

the project actually "restrict" sanic and aiohttp version. Since  18.12.0 is the LTS version of sanic , maybe an update is possible ?

sanic-openid-connect-provider 0.4.8 has requirement aiohttp==3.4.4, but you'll have aiohttp 3.5.4 which is incompatible.
sanic-openid-connect-provider 0.4.8 has requirement sanic==0.8.3, but you'll have sanic 18.12.0 which is incompatible.

by the way , the plugin work correctly with theses versions.

**Comment by terricain** [comment]
Ah yeah, I'll revise the deps :smile:

**Comment by terricain** [comment]
I've relaxed the dependencies a lot. Give 0.5.0 (4303ee76ff3dcbad2854c38b3097929e3d3a8c33) a go. Have moved the aioboto3 and aioredis into extra_requires so its not dragged in with the main client.

**Comment by raphaelauv** [comment]
That's really nice , thank you

**Comment by terricain** [comment]
Np
